# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 18:03
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import projeto.models.template
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, default=1)),
                ('nome', models.CharField(blank=True, max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('indicador_fisico', models.CharField(blank=True, max_length=32, validators=[django.core.validators.MinLengthValidator(2)])),
                ('peso_planoacao', models.PositiveIntegerField(blank=True, default=1)),
                ('data_inicio', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('data_fim', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ManyToManyField(blank=True, related_name='colaborador_atividade', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'atividade',
                'ordering': ['nome'],
                'verbose_name_plural': 'atividades',
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(2)])),
                ('nome', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(5)])),
                ('site', models.CharField(blank=True, max_length=128, validators=[django.core.validators.MinLengthValidator(5)])),
                ('email', models.CharField(blank=True, max_length=256, validators=[django.core.validators.EmailValidator()])),
                ('endereco', models.CharField(blank=True, max_length=256, validators=[django.core.validators.MinLengthValidator(2)])),
                ('cidade', models.CharField(blank=True, max_length=256, validators=[django.core.validators.MinLengthValidator(2)])),
                ('descricao', models.TextField(blank=True, max_length=512, validators=[django.core.validators.MinLengthValidator(10)])),
                ('cnpj', models.CharField(blank=True, max_length=14)),
                ('telefone', models.CharField(blank=True, max_length=16)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=16)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'instituição',
                'ordering': ['sigla'],
                'verbose_name_plural': 'instituições',
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.CreateModel(
            name='MetaProjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1)),
                ('nome', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(5)])),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'meta',
                'ordering': ['nome'],
                'verbose_name_plural': 'metas',
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1)),
                ('descricao', models.TextField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'objetivo',
                'ordering': ['descricao'],
                'verbose_name_plural': 'objetivos',
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.CreateModel(
            name='PalavraChave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(2)])),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'palavra chave',
                'ordering': ['palavra'],
                'verbose_name_plural': 'palavras chave',
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.CreateModel(
            name='PlanoAcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1)),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('codigo_seg', models.CharField(blank=True, max_length=32, validators=[django.core.validators.MinLengthValidator(2)])),
                ('data_inicio', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('data_fim', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'plano de ação',
                'ordering': ['nome'],
                'verbose_name_plural': 'planos de ação',
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seg', models.CharField(blank=True, max_length=32, validators=[django.core.validators.MinLengthValidator(2)])),
                ('titulo_portugues', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(5)])),
                ('titulo_ingles', models.CharField(blank=True, max_length=256, validators=[django.core.validators.MinLengthValidator(5)])),
                ('sigla', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(2)])),
                ('data_inicio', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('duracao', models.IntegerField(blank=True, default=1)),
                ('hipotese', models.TextField(blank=True)),
                ('objetivo_geral', models.TextField(blank=True)),
                ('resumo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PLAN', 'Planejamento'), ('AVAL', 'Em Avaliação'), ('EXEC', 'Em Execução'), ('FINA', 'Finalizado')], default='PLAN', max_length=64)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criado', to=settings.AUTH_USER_MODEL)),
                ('instituicao_executora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executora', to='projeto.Instituicao')),
                ('instituicao_proponente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proponente', to='projeto.Instituicao')),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lider', to=settings.AUTH_USER_MODEL)),
                ('projeto_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relacionado', to='projeto.Projeto')),
            ],
            options={
                'verbose_name': 'projeto',
                'ordering': ['sigla'],
                'verbose_name_plural': 'projetos',
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.CreateModel(
            name='ProjetoComponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1)),
                ('nome', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(5)])),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'projeto componente',
                'ordering': ['nome'],
                'verbose_name_plural': 'projetos componentees',
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1)),
                ('descricao', models.TextField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('objetivo', smart_selects.db_fields.ChainedManyToManyField(chained_field='projeto', chained_model_field='projeto', to='projeto.Objetivo')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto')),
            ],
            options={
                'verbose_name': 'resultado',
                'ordering': ['numero'],
                'verbose_name_plural': 'resultados',
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, default=1)),
                ('nome', models.CharField(blank=True, max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('indicador_fisico', models.CharField(blank=True, max_length=32, validators=[django.core.validators.MinLengthValidator(2)])),
                ('peso_atividade', models.PositiveIntegerField(blank=True, default=1)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('atividade', smart_selects.db_fields.ChainedForeignKey(chained_field='planoacao', chained_model_field='planoacao', on_delete=django.db.models.deletion.CASCADE, to='projeto.Atividade')),
                ('colaborador', models.ManyToManyField(blank=True, related_name='colaborador_tarefa', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('planoacao', smart_selects.db_fields.ChainedForeignKey(chained_field='projeto', chained_model_field='projeto', on_delete=django.db.models.deletion.CASCADE, to='projeto.PlanoAcao')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_tarefa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tarefa',
                'ordering': ['nome'],
                'verbose_name_plural': 'tarefas',
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.AddField(
            model_name='planoacao',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto'),
        ),
        migrations.AddField(
            model_name='planoacao',
            name='projeto_componente',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='projeto', chained_model_field='projeto', on_delete=django.db.models.deletion.CASCADE, to='projeto.ProjetoComponente'),
        ),
        migrations.AddField(
            model_name='planoacao',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_plano', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planoacao',
            name='resultado',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='projeto', chained_model_field='projeto', to='projeto.Resultado'),
        ),
        migrations.AddField(
            model_name='palavrachave',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto'),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto'),
        ),
        migrations.AddField(
            model_name='metaprojeto',
            name='objetivo',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='projeto', chained_model_field='projeto', to='projeto.Objetivo'),
        ),
        migrations.AddField(
            model_name='metaprojeto',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='planoacao',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='projeto', chained_model_field='projeto', on_delete=django.db.models.deletion.CASCADE, to='projeto.PlanoAcao'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_atividade', to=settings.AUTH_USER_MODEL),
        ),
    ]
