# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='palavrachave',
            options={'ordering': ['palavra'], 'verbose_name': 'palavra chave', 'verbose_name_plural': 'palavras chave'},
        ),
        migrations.RemoveField(
            model_name='palavrachave',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='palavra_chave',
        ),
        migrations.AddField(
            model_name='palavrachave',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
    ]
