# Generated by Django 2.0.4 on 2018-04-12 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='colaborador',
            field=models.ManyToManyField(blank=True, related_name='colaborador_projeto', to=settings.AUTH_USER_MODEL),
        ),
    ]
