# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projetocomponente',
            options={'ordering': ['nome'], 'verbose_name': 'projeto componente', 'verbose_name_plural': 'projetos componentes'},
        ),
    ]
