# Generated by Django 2.0.4 on 2018-04-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_projeto_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='blast',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='jbrowse',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='resultados',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='planoacao',
        ),
        migrations.AddField(
            model_name='atividade',
            name='planoacao',
            field=models.ManyToManyField(blank=True, related_name='PlanoAcao', to='projeto.PlanoAcao'),
        ),
        migrations.AlterField(
            model_name='metaprojeto',
            name='objetivo',
            field=models.ManyToManyField(blank=True, related_name='objetivo_metaprojeto', to='projeto.Objetivo'),
        ),
        migrations.RemoveField(
            model_name='planoacao',
            name='projeto_componente',
        ),
        migrations.AddField(
            model_name='planoacao',
            name='projeto_componente',
            field=models.ManyToManyField(blank=True, related_name='projeto_componente', to='projeto.ProjetoComponente'),
        ),
        migrations.AlterField(
            model_name='planoacao',
            name='resultado',
            field=models.ManyToManyField(blank=True, related_name='resultado', to='projeto.Resultado'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='objetivo',
            field=models.ManyToManyField(blank=True, related_name='objetivo', to='projeto.Objetivo'),
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='atividade',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='atividade',
            field=models.ManyToManyField(blank=True, related_name='atividade', to='projeto.Atividade'),
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='planoacao',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='planoacao',
            field=models.ManyToManyField(blank=True, related_name='planoacao', to='projeto.PlanoAcao'),
        ),
    ]
