# Generated by Django 2.0.4 on 2018-04-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0003_auto_20180416_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='blast',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='jbrowse',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
