# Generated by Django 2.0.4 on 2021-09-22 18:55

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0004_auto_20180418_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='planoacao',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, blank=True, chained_field='projeto', chained_model_field='projeto', to='projeto.PlanoAcao'),
        ),
        migrations.AlterField(
            model_name='metaprojeto',
            name='objetivo',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, blank=True, chained_field='projeto', chained_model_field='projeto', to='projeto.Objetivo'),
        ),
        migrations.AlterField(
            model_name='planoacao',
            name='projeto_componente',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, blank=True, chained_field='projeto', chained_model_field='projeto', to='projeto.ProjetoComponente'),
        ),
        migrations.AlterField(
            model_name='planoacao',
            name='resultado',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, blank=True, chained_field='projeto', chained_model_field='projeto', to='projeto.Resultado'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='resultados',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='objetivo',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, blank=True, chained_field='projeto', chained_model_field='projeto', to='projeto.Objetivo'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='atividade',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, blank=True, chained_field='projeto', chained_model_field='projeto', to='projeto.Atividade'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='planoacao',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, blank=True, chained_field='projeto', chained_model_field='projeto', to='projeto.PlanoAcao'),
        ),
    ]
