# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 16:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projeto.models.template


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'analytical methods',
                'ordering': ['name'],
                'verbose_name': 'analytical method',
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.CreateModel(
            name='Approach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'approaches',
                'ordering': ['name'],
                'verbose_name': 'approach',
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'databases',
                'ordering': ['name'],
                'verbose_name': 'database',
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'equipments',
                'ordering': ['name'],
                'verbose_name': 'equipment',
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=150)),
                ('chemical_formula', models.CharField(max_length=150)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'formulae',
                'ordering': ['common_name'],
                'verbose_name': 'formula',
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('experimental_condition', models.TextField(blank=True)),
                ('lc_method', models.FileField(blank=True, null=True, upload_to='bmdb/raw/%Y/%m/%d/')),
                ('ms_method', models.FileField(blank=True, null=True, upload_to='bmdb/raw/%Y/%m/%d/')),
                ('parameters', models.FileField(blank=True, null=True, upload_to='bmdb/raw/%Y/%m/%d/')),
                ('sample_preparation', models.FileField(blank=True, null=True, upload_to='bmdb/raw/%Y/%m/%d/')),
                ('raw_data', models.FileField(blank=True, null=True, upload_to='bmdb/raw/%Y/%m/%d/')),
                ('processed_data', models.FileField(blank=True, null=True, upload_to='bmdb/raw/%Y/%m/%d/')),
                ('csv', models.FileField(blank=True, null=True, upload_to='bmdb/raw/%Y/%m/%d/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bmdb/raw/%Y/%m/%d/')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('analytical_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_analytical', to='metabolomica.Analytical')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ManyToManyField(blank=True, related_name='result_equipment', to='metabolomica.Equipment')),
            ],
            options={
                'verbose_name_plural': 'results',
                'ordering': ['name'],
                'verbose_name': 'result',
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_code', models.CharField(max_length=64, unique=True)),
                ('replicate', models.CharField(blank=True, max_length=64)),
                ('bio_sample', models.CharField(blank=True, max_length=64)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('database', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metabolomica.Database')),
            ],
            options={
                'verbose_name_plural': 'samples',
                'ordering': ['-data_atualizado'],
                'verbose_name': 'sample',
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('scientific_name', models.CharField(max_length=150)),
                ('strain', models.CharField(blank=True, max_length=64, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'species',
                'ordering': ['name'],
                'verbose_name': 'species',
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.AddField(
            model_name='sample',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metabolomica.Species'),
        ),
        migrations.AddField(
            model_name='result',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_sample', to='metabolomica.Sample'),
        ),
    ]
