# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 10:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projeto.models.template


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projeto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'database',
                'verbose_name_plural': 'databases',
                'ordering': ['name'],
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'equipment',
                'verbose_name_plural': 'equipments',
                'ordering': ['name'],
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto')),
            ],
            options={
                'verbose_name': 'experiment',
                'verbose_name_plural': 'experiments',
                'ordering': ['name'],
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('experimental_condition', models.TextField(blank=True)),
                ('analytical_method', models.CharField(blank=True, max_length=40)),
                ('equip_mode', models.CharField(blank=True, max_length=40, null=True)),
                ('extr_method', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/')),
                ('parameters_lc_ms', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/')),
                ('lc_raw_data', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/')),
                ('ms_raw_data', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/')),
                ('raw_data', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/')),
                ('process_data', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ManyToManyField(blank=True, related_name='result_equipment', to='metabolomica.Equipment')),
            ],
            options={
                'verbose_name': 'result',
                'verbose_name_plural': 'results',
                'ordering': ['name'],
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_code', models.CharField(max_length=64)),
                ('replicate', models.CharField(blank=True, max_length=64)),
                ('species', models.CharField(blank=True, max_length=64)),
                ('bio_sample', models.CharField(blank=True, max_length=64)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('database', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metabolomica.Database')),
            ],
            options={
                'verbose_name': 'sample',
                'verbose_name_plural': 'samples',
                'ordering': ['lab_code'],
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.AddField(
            model_name='result',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metabolomica.Sample'),
        ),
    ]
