# Generated by Django 2.0.4 on 2018-04-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabolomica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analytical',
            options={'ordering': ['name'], 'verbose_name': 'analytical', 'verbose_name_plural': 'analyticals'},
        ),
        migrations.AlterField(
            model_name='result',
            name='equipment',
            field=models.ManyToManyField(blank=True, help_text="Hold 'Crtl' or 'Shift' for multiple selection.", related_name='result_equipment', to='metabolomica.Equipment'),
        ),
    ]
