# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_auto_20161116_1514'),
        ('metabolomica', '0003_equipment_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['name'], 'verbose_name': 'result', 'verbose_name_plural': 'results'},
        ),
    ]
