# Generated by Django 2.0.4 on 2021-10-05 20:22

from django.db import migrations, models
import django.db.models.deletion
import projeto.models.template


class Migration(migrations.Migration):

    dependencies = [
        ('ssrnai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percevejo_Iscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fragment_seq', models.TextField(max_length=100, verbose_name='fragment_seq')),
                ('start', models.IntegerField(verbose_name='start')),
                ('end', models.IntegerField(verbose_name='end')),
                ('hits', models.IntegerField(verbose_name='hits')),
                ('hits_description', models.TextField(verbose_name='hits_description')),
                ('gene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Percevejo_Gene_Information')),
                ('organism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Organisms')),
            ],
            options={
                'verbose_name': 'dsrna',
                'verbose_name_plural': 'dsrnas',
                'ordering': ['id'],
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.CreateModel(
            name='Percevejo_Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mismatch', models.IntegerField(verbose_name='mismatch')),
                ('match', models.IntegerField(verbose_name='match')),
                ('composition', models.TextField(verbose_name='composition')),
                ('classification', models.CharField(max_length=50, verbose_name='classification')),
                ('interaction_energy', models.FloatField(max_length=50, verbose_name='interaction_energy')),
                ('figure', models.CharField(max_length=500, verbose_name='figure')),
                ('dsrna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Percevejo_Dsrna_Information')),
                ('gene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Percevejo_Gene_Information')),
                ('organism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Organisms')),
            ],
            options={
                'verbose_name': 'dsrna',
                'verbose_name_plural': 'dsrnas',
                'ordering': ['id'],
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
    ]
