# Generated by Django 2.0.4 on 2021-09-30 12:36

from django.db import migrations, models
import projeto.models.template


class Migration(migrations.Migration):

    dependencies = [
        ('ssrnai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organism_name', models.CharField(max_length=150, unique=True, verbose_name='organism_name')),
                ('common_name', models.CharField(max_length=150, verbose_name='common_name')),
                ('taxonomy', models.CharField(blank=True, max_length=500, null=True, verbose_name='taxonomy')),
            ],
            options={
                'verbose_name': 'organism',
                'verbose_name_plural': 'organisms',
                'ordering': ['organism_name'],
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
    ]
