# Generated by Django 2.0.4 on 2021-10-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssrnai', '0002_percevejo_iscore_percevejo_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capim_gene_information',
            name='cds_seq',
            field=models.TextField(blank=True, null=True, verbose_name='cds_seq'),
        ),
        migrations.AlterField(
            model_name='capim_gene_information',
            name='gene_description',
            field=models.TextField(blank=True, null=True, verbose_name='gene_description'),
        ),
        migrations.AlterField(
            model_name='capim_gene_information',
            name='gene_name',
            field=models.CharField(max_length=250, verbose_name='gene_name'),
        ),
        migrations.AlterField(
            model_name='capim_gene_information',
            name='gene_ontology_blastx',
            field=models.TextField(blank=True, null=True, verbose_name='gene_ontology_blastx'),
        ),
        migrations.AlterField(
            model_name='capim_gene_information',
            name='gene_ontology_pfam',
            field=models.TextField(blank=True, null=True, verbose_name='kegene_ontology_pfamgg'),
        ),
        migrations.AlterField(
            model_name='capim_gene_information',
            name='kegg',
            field=models.TextField(blank=True, null=True, verbose_name='kegg'),
        ),
        migrations.AlterField(
            model_name='capim_gene_information',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='capim_gene_information',
            name='pfam',
            field=models.TextField(blank=True, null=True, verbose_name='pfam'),
        ),
        migrations.AlterField(
            model_name='capim_gene_information',
            name='sprot_top_blastx_hit',
            field=models.TextField(blank=True, null=True, verbose_name='sprot_top_blastx_hit'),
        ),
        migrations.AlterField(
            model_name='conyza_gene_information',
            name='cds_seq',
            field=models.TextField(blank=True, null=True, verbose_name='cds_seq'),
        ),
        migrations.AlterField(
            model_name='conyza_gene_information',
            name='gene_description',
            field=models.TextField(blank=True, null=True, verbose_name='gene_description'),
        ),
        migrations.AlterField(
            model_name='conyza_gene_information',
            name='gene_name',
            field=models.CharField(max_length=250, verbose_name='gene_name'),
        ),
        migrations.AlterField(
            model_name='conyza_gene_information',
            name='gene_ontology_blastx',
            field=models.TextField(blank=True, null=True, verbose_name='gene_ontology_blastx'),
        ),
        migrations.AlterField(
            model_name='conyza_gene_information',
            name='gene_ontology_pfam',
            field=models.TextField(blank=True, null=True, verbose_name='kegene_ontology_pfamgg'),
        ),
        migrations.AlterField(
            model_name='conyza_gene_information',
            name='kegg',
            field=models.TextField(blank=True, null=True, verbose_name='kegg'),
        ),
        migrations.AlterField(
            model_name='conyza_gene_information',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='conyza_gene_information',
            name='pfam',
            field=models.TextField(blank=True, null=True, verbose_name='pfam'),
        ),
        migrations.AlterField(
            model_name='conyza_gene_information',
            name='sprot_top_blastx_hit',
            field=models.TextField(blank=True, null=True, verbose_name='sprot_top_blastx_hit'),
        ),
        migrations.AlterField(
            model_name='lagarta_gene_information',
            name='cds_seq',
            field=models.TextField(blank=True, null=True, verbose_name='cds_seq'),
        ),
        migrations.AlterField(
            model_name='lagarta_gene_information',
            name='gene_description',
            field=models.TextField(blank=True, null=True, verbose_name='gene_description'),
        ),
        migrations.AlterField(
            model_name='lagarta_gene_information',
            name='gene_name',
            field=models.CharField(max_length=250, verbose_name='gene_name'),
        ),
        migrations.AlterField(
            model_name='lagarta_gene_information',
            name='gene_ontology_blastx',
            field=models.TextField(blank=True, null=True, verbose_name='gene_ontology_blastx'),
        ),
        migrations.AlterField(
            model_name='lagarta_gene_information',
            name='gene_ontology_pfam',
            field=models.TextField(blank=True, null=True, verbose_name='kegene_ontology_pfamgg'),
        ),
        migrations.AlterField(
            model_name='lagarta_gene_information',
            name='kegg',
            field=models.TextField(blank=True, null=True, verbose_name='kegg'),
        ),
        migrations.AlterField(
            model_name='lagarta_gene_information',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='lagarta_gene_information',
            name='pfam',
            field=models.TextField(blank=True, null=True, verbose_name='pfam'),
        ),
        migrations.AlterField(
            model_name='lagarta_gene_information',
            name='sprot_top_blastx_hit',
            field=models.TextField(blank=True, null=True, verbose_name='sprot_top_blastx_hit'),
        ),
        migrations.AlterField(
            model_name='nematoide_gene_information',
            name='cds_seq',
            field=models.TextField(blank=True, null=True, verbose_name='cds_seq'),
        ),
        migrations.AlterField(
            model_name='nematoide_gene_information',
            name='gene_description',
            field=models.TextField(blank=True, null=True, verbose_name='gene_description'),
        ),
        migrations.AlterField(
            model_name='nematoide_gene_information',
            name='gene_name',
            field=models.CharField(max_length=250, verbose_name='gene_name'),
        ),
        migrations.AlterField(
            model_name='nematoide_gene_information',
            name='gene_ontology_blastx',
            field=models.TextField(blank=True, null=True, verbose_name='gene_ontology_blastx'),
        ),
        migrations.AlterField(
            model_name='nematoide_gene_information',
            name='gene_ontology_pfam',
            field=models.TextField(blank=True, null=True, verbose_name='kegene_ontology_pfamgg'),
        ),
        migrations.AlterField(
            model_name='nematoide_gene_information',
            name='kegg',
            field=models.TextField(blank=True, null=True, verbose_name='kegg'),
        ),
        migrations.AlterField(
            model_name='nematoide_gene_information',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='nematoide_gene_information',
            name='pfam',
            field=models.TextField(blank=True, null=True, verbose_name='pfam'),
        ),
        migrations.AlterField(
            model_name='nematoide_gene_information',
            name='sprot_top_blastx_hit',
            field=models.TextField(blank=True, null=True, verbose_name='sprot_top_blastx_hit'),
        ),
        migrations.AlterField(
            model_name='percevejo_gene_information',
            name='cds_seq',
            field=models.TextField(blank=True, null=True, verbose_name='cds_seq'),
        ),
        migrations.AlterField(
            model_name='percevejo_gene_information',
            name='gene_description',
            field=models.TextField(blank=True, null=True, verbose_name='gene_description'),
        ),
        migrations.AlterField(
            model_name='percevejo_gene_information',
            name='gene_name',
            field=models.CharField(max_length=250, verbose_name='gene_name'),
        ),
        migrations.AlterField(
            model_name='percevejo_gene_information',
            name='gene_ontology_blastx',
            field=models.TextField(blank=True, null=True, verbose_name='gene_ontology_blastx'),
        ),
        migrations.AlterField(
            model_name='percevejo_gene_information',
            name='gene_ontology_pfam',
            field=models.TextField(blank=True, null=True, verbose_name='kegene_ontology_pfamgg'),
        ),
        migrations.AlterField(
            model_name='percevejo_gene_information',
            name='kegg',
            field=models.TextField(blank=True, null=True, verbose_name='kegg'),
        ),
        migrations.AlterField(
            model_name='percevejo_gene_information',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='percevejo_gene_information',
            name='pfam',
            field=models.TextField(blank=True, null=True, verbose_name='pfam'),
        ),
        migrations.AlterField(
            model_name='percevejo_gene_information',
            name='sprot_top_blastx_hit',
            field=models.TextField(blank=True, null=True, verbose_name='sprot_top_blastx_hit'),
        ),
    ]
