# Generated by Django 2.0.4 on 2021-09-30 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssrnai', '0002_organism'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='database_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Database'),
        ),
    ]
