# Generated by Django 2.0.4 on 2021-10-08 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssrnai', '0003_auto_20211006_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='percevejo_dsrna_information',
            name='gene',
        ),
        migrations.AddField(
            model_name='percevejo_dsrna_information',
            name='gene_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Percevejo_Gene_Information'),
        ),
    ]
