# Generated by Django 2.0.4 on 2021-09-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssrnai', '0003_organism_database_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organism',
            old_name='database_id',
            new_name='database',
        ),
        migrations.AlterField(
            model_name='organism',
            name='taxonomy',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='taxonomy'),
        ),
    ]
