# Generated by Django 2.0.4 on 2021-10-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssrnai', '0004_auto_20211008_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='percevejo_dsrna_information',
            old_name='gene_name',
            new_name='gene',
        ),
    ]
