# Generated by Django 2.0.4 on 2021-10-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssrnai', '0005_auto_20211008_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='percevejo_dsrna_information',
            name='offtarget_image',
            field=models.TextField(blank=True, null=True, verbose_name='offtarget_image'),
        ),
        migrations.AlterField(
            model_name='percevejo_dsrna_information',
            name='dsrna_seq',
            field=models.TextField(blank=True, null=True, verbose_name='dsrna_seq'),
        ),
        migrations.AlterField(
            model_name='percevejo_dsrna_information',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='percevejo_dsrna_information',
            name='start',
            field=models.IntegerField(blank=True, null=True, verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='percevejo_dsrna_information',
            name='stop',
            field=models.IntegerField(blank=True, null=True, verbose_name='stop'),
        ),
    ]
