# Generated by Django 2.0.4 on 2021-10-09 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssrnai', '0006_auto_20211008_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='percevejo_iscore',
            options={'ordering': ['id'], 'verbose_name': 'iscore', 'verbose_name_plural': 'iscores'},
        ),
        migrations.RemoveField(
            model_name='percevejo_iscore',
            name='end',
        ),
        migrations.RemoveField(
            model_name='percevejo_iscore',
            name='fragment_seq',
        ),
        migrations.RemoveField(
            model_name='percevejo_iscore',
            name='hits',
        ),
        migrations.RemoveField(
            model_name='percevejo_iscore',
            name='hits_description',
        ),
        migrations.RemoveField(
            model_name='percevejo_iscore',
            name='start',
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='count_dsir',
            field=models.FloatField(blank=True, null=True, verbose_name='count_dsir'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='count_iscore',
            field=models.FloatField(blank=True, null=True, verbose_name='count_iscore'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='count_sbiopredsi',
            field=models.FloatField(blank=True, null=True, verbose_name='count_iscore'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='dsrna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Percevejo_Dsrna_Information'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='max_dsir',
            field=models.FloatField(blank=True, null=True, verbose_name='max_dsir'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='max_iscore',
            field=models.FloatField(blank=True, null=True, verbose_name='max_iscore'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='max_sbiopredsi',
            field=models.FloatField(blank=True, null=True, verbose_name='max_iscore'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='mean_dsir',
            field=models.FloatField(blank=True, null=True, verbose_name='mean_dsir'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='mean_iscore',
            field=models.FloatField(blank=True, null=True, verbose_name='mean_iscore'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='mean_sbiopredsi',
            field=models.FloatField(blank=True, null=True, verbose_name='mean_iscore'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='median_dsir',
            field=models.FloatField(blank=True, null=True, verbose_name='median_dsir'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='median_iscore',
            field=models.FloatField(blank=True, null=True, verbose_name='median_iscore'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='median_sbiopredsi',
            field=models.FloatField(blank=True, null=True, verbose_name='median_iscore'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='min_dsir',
            field=models.FloatField(blank=True, null=True, verbose_name='min_dsir'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='min_iscore',
            field=models.FloatField(blank=True, null=True, verbose_name='min_iscore'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='min_sbiopredsi',
            field=models.FloatField(blank=True, null=True, verbose_name='min_iscore'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='rank_dsir',
            field=models.IntegerField(blank=True, null=True, verbose_name='rank_dsir'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='rank_iscore',
            field=models.IntegerField(blank=True, null=True, verbose_name='rank_iscore'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='rank_sbiopredsi',
            field=models.IntegerField(blank=True, null=True, verbose_name='rank_sbiopredsi'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='std_dsir',
            field=models.FloatField(blank=True, null=True, verbose_name='std_dsir'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='std_iscore',
            field=models.FloatField(blank=True, null=True, verbose_name='std_iscore'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='std_sbiopredsi',
            field=models.FloatField(blank=True, null=True, verbose_name='std_iscore'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='sum_dsir',
            field=models.FloatField(blank=True, null=True, verbose_name='sum_dsir'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='sum_iscore',
            field=models.FloatField(blank=True, null=True, verbose_name='sum_iscore'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='sum_sbiopredsi',
            field=models.FloatField(blank=True, null=True, verbose_name='sum_iscore'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='var_dsir',
            field=models.FloatField(blank=True, null=True, verbose_name='var_dsir'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='var_iscore',
            field=models.FloatField(blank=True, null=True, verbose_name='var_iscore'),
        ),
        migrations.AddField(
            model_name='percevejo_iscore',
            name='var_sbiopredsi',
            field=models.FloatField(blank=True, null=True, verbose_name='var_iscore'),
        ),
    ]
