# Generated by Django 2.0.4 on 2021-09-30 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssrnai', '0006_auto_20210930_0953'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organism',
            new_name='Organisms',
        ),
    ]
