# Generated by Django 2.0.4 on 2021-10-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssrnai', '0007_auto_20211009_1417'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Percevejo_Dsrna_Information',
            new_name='PercevejoDsrnaInformation',
        ),
    ]
