# Generated by Django 2.0.4 on 2021-10-11 22:36

from django.db import migrations, models
import django.db.models.deletion
import projeto.models.template


class Migration(migrations.Migration):

    dependencies = [
        ('ssrnai', '0008_auto_20211011_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percevejo_Expression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eheros_fat_body1', models.FloatField(blank=True, null=True, verbose_name='eheros_fat_body1')),
                ('eheros_fat_body2', models.FloatField(blank=True, null=True, verbose_name='eheros_fat_body2')),
                ('eheros_fat_body3', models.FloatField(blank=True, null=True, verbose_name='eheros_fat_body3')),
                ('eheros_fat_body4', models.FloatField(blank=True, null=True, verbose_name='eheros_fat_body4')),
                ('eheros_gut1', models.FloatField(blank=True, null=True, verbose_name='eheros_gut1')),
                ('eheros_fat_body5', models.FloatField(blank=True, null=True, verbose_name='eheros_fat_body5')),
                ('eheros_gut2', models.FloatField(blank=True, null=True, verbose_name='eheros_gut2')),
                ('eheros_gut3', models.FloatField(blank=True, null=True, verbose_name='eheros_gut3')),
                ('eheros_gut4', models.FloatField(blank=True, null=True, verbose_name='eheros_gut4')),
                ('eheros_gut5', models.FloatField(blank=True, null=True, verbose_name='eheros_gut5')),
                ('eheros_gut6', models.FloatField(blank=True, null=True, verbose_name='eheros_gut6')),
                ('eheros_gut7', models.FloatField(blank=True, null=True, verbose_name='eheros_gut7')),
                ('eheros_gut8', models.FloatField(blank=True, null=True, verbose_name='eheros_gut8')),
                ('eheros_gut9', models.FloatField(blank=True, null=True, verbose_name='eheros_gut9')),
                ('eheros_gut10', models.FloatField(blank=True, null=True, verbose_name='eheros_gut10')),
                ('eheros_gut11', models.FloatField(blank=True, null=True, verbose_name='eheros_gut11')),
                ('eheros_gut12', models.FloatField(blank=True, null=True, verbose_name='eheros_gut12')),
                ('eheros_gut13', models.FloatField(blank=True, null=True, verbose_name='eheros_gut13')),
                ('gene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Percevejo_Gene_Information')),
                ('organism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Organisms')),
            ],
            options={
                'verbose_name': 'dicer',
                'verbose_name_plural': 'dicers',
                'ordering': ['id'],
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
    ]
