# Generated by Django 2.0.4 on 2021-10-13 13:50

from django.db import migrations, models
import django.db.models.deletion
import projeto.models.template


class Migration(migrations.Migration):

    dependencies = [
        ('ssrnai', '0010_auto_20211012_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percevejo_On_Targets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_ontarget', models.IntegerField(blank=True, null=True, verbose_name='number_ontarget')),
                ('start_dsrna', models.IntegerField(blank=True, null=True, verbose_name='start_dsrna')),
                ('end_dsrna', models.IntegerField(blank=True, null=True, verbose_name='end_dsrna')),
                ('dsrna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.PercevejoDsrnaInformation')),
                ('gene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Percevejo_Gene_Information')),
                ('organism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Organisms')),
            ],
            options={
                'verbose_name': 'ontarget',
                'verbose_name_plural': 'ontargets',
                'ordering': ['id'],
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
    ]
