# Generated by Django 2.0.4 on 2021-10-14 00:22

from django.db import migrations, models
import django.db.models.deletion
import projeto.models.template


class Migration(migrations.Migration):

    dependencies = [
        ('ssrnai', '0011_percevejo_on_targets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capim_Expression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exilis_Spike', models.FloatField(blank=True, null=True, verbose_name='exilis_Spike')),
                ('exilis_Grain', models.FloatField(blank=True, null=True, verbose_name='exilis_Grain')),
                ('exilis_Seedling', models.FloatField(blank=True, null=True, verbose_name='exilis_Seedling')),
                ('exilis_leaf', models.FloatField(blank=True, null=True, verbose_name='exilis_leaf')),
                ('exilis_whole', models.FloatField(blank=True, null=True, verbose_name='exilis_whole')),
                ('eriantha_whole', models.FloatField(blank=True, null=True, verbose_name='eriantha_whole')),
                ('cuyabensis_whole', models.FloatField(blank=True, null=True, verbose_name='cuyabensis_whole')),
                ('sanguinalis_Resist1', models.FloatField(blank=True, null=True, verbose_name='sanguinalis_Resist1')),
                ('sanguinalis_Resist2', models.FloatField(blank=True, null=True, verbose_name='sanguinalis_Resist2')),
                ('sanguinalis_Suscep1', models.FloatField(blank=True, null=True, verbose_name='sanguinalis_Suscep1')),
                ('sanguinalis_Suscep2', models.FloatField(blank=True, null=True, verbose_name='sanguinalis_Suscep2')),
                ('ciliaris_leaves', models.FloatField(blank=True, null=True, verbose_name='ciliaris_leaves')),
                ('ciliaris_roots', models.FloatField(blank=True, null=True, verbose_name='ciliaris_roots')),
                ('ciliaris_leave', models.FloatField(blank=True, null=True, verbose_name='ciliaris_leave')),
                ('ciliaris_root', models.FloatField(blank=True, null=True, verbose_name='ciliaris_root')),
                ('milanjiana_Whole', models.FloatField(blank=True, null=True, verbose_name='milanjiana_Whole')),
                ('californica_leaf1', models.FloatField(blank=True, null=True, verbose_name='californica_leaf1')),
                ('californica_leaf2', models.FloatField(blank=True, null=True, verbose_name='californica_leaf2')),
                ('californica_leaf3', models.FloatField(blank=True, null=True, verbose_name='californica_leaf3')),
                ('californica_leaf4', models.FloatField(blank=True, null=True, verbose_name='californica_leaf4')),
                ('californica_leaf5', models.FloatField(blank=True, null=True, verbose_name='californica_leaf5')),
                ('californica_leaf6', models.FloatField(blank=True, null=True, verbose_name='californica_leaf6')),
                ('ciliaris_Resist1', models.FloatField(blank=True, null=True, verbose_name='ciliaris_Resist1')),
                ('ciliaris_Resist2', models.FloatField(blank=True, null=True, verbose_name='ciliaris_Resist2')),
                ('gene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Capim_Gene_Information')),
                ('organism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Organisms')),
            ],
            options={
                'verbose_name': 'dicer',
                'verbose_name_plural': 'dicers',
                'ordering': ['id'],
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.CreateModel(
            name='Capim_Iscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_dsir', models.IntegerField(blank=True, null=True, verbose_name='rank_dsir')),
                ('rank_iscore', models.IntegerField(blank=True, null=True, verbose_name='rank_iscore')),
                ('rank_sbiopredsi', models.IntegerField(blank=True, null=True, verbose_name='rank_sbiopredsi')),
                ('mean_dsir', models.FloatField(blank=True, null=True, verbose_name='mean_dsir')),
                ('sum_dsir', models.FloatField(blank=True, null=True, verbose_name='sum_dsir')),
                ('max_dsir', models.FloatField(blank=True, null=True, verbose_name='max_dsir')),
                ('min_dsir', models.FloatField(blank=True, null=True, verbose_name='min_dsir')),
                ('count_dsir', models.FloatField(blank=True, null=True, verbose_name='count_dsir')),
                ('median_dsir', models.FloatField(blank=True, null=True, verbose_name='median_dsir')),
                ('std_dsir', models.FloatField(blank=True, null=True, verbose_name='std_dsir')),
                ('var_dsir', models.FloatField(blank=True, null=True, verbose_name='var_dsir')),
                ('mean_iscore', models.FloatField(blank=True, null=True, verbose_name='mean_iscore')),
                ('sum_iscore', models.FloatField(blank=True, null=True, verbose_name='sum_iscore')),
                ('max_iscore', models.FloatField(blank=True, null=True, verbose_name='max_iscore')),
                ('min_iscore', models.FloatField(blank=True, null=True, verbose_name='min_iscore')),
                ('count_iscore', models.FloatField(blank=True, null=True, verbose_name='count_iscore')),
                ('median_iscore', models.FloatField(blank=True, null=True, verbose_name='median_iscore')),
                ('std_iscore', models.FloatField(blank=True, null=True, verbose_name='std_iscore')),
                ('var_iscore', models.FloatField(blank=True, null=True, verbose_name='var_iscore')),
                ('mean_sbiopredsi', models.FloatField(blank=True, null=True, verbose_name='mean_iscore')),
                ('sum_sbiopredsi', models.FloatField(blank=True, null=True, verbose_name='sum_iscore')),
                ('max_sbiopredsi', models.FloatField(blank=True, null=True, verbose_name='max_iscore')),
                ('min_sbiopredsi', models.FloatField(blank=True, null=True, verbose_name='min_iscore')),
                ('count_sbiopredsi', models.FloatField(blank=True, null=True, verbose_name='count_iscore')),
                ('median_sbiopredsi', models.FloatField(blank=True, null=True, verbose_name='median_iscore')),
                ('std_sbiopredsi', models.FloatField(blank=True, null=True, verbose_name='std_iscore')),
                ('var_sbiopredsi', models.FloatField(blank=True, null=True, verbose_name='var_iscore')),
            ],
            options={
                'verbose_name': 'iscore',
                'verbose_name_plural': 'iscores',
                'ordering': ['id'],
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.CreateModel(
            name='Capim_On_Targets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_ontarget', models.IntegerField(blank=True, null=True, verbose_name='number_ontarget')),
                ('start_dsrna', models.IntegerField(blank=True, null=True, verbose_name='start_dsrna')),
                ('end_dsrna', models.IntegerField(blank=True, null=True, verbose_name='end_dsrna')),
            ],
            options={
                'verbose_name': 'ontarget',
                'verbose_name_plural': 'ontargets',
                'ordering': ['id'],
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.CreateModel(
            name='Capim_Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mismatch', models.IntegerField(blank=True, null=True, verbose_name='mismatch')),
                ('match', models.IntegerField(blank=True, null=True, verbose_name='match')),
                ('composition', models.TextField(blank=True, null=True, verbose_name='composition')),
                ('classification', models.CharField(max_length=50, null=True, verbose_name='classification')),
                ('interaction_energy', models.FloatField(blank=True, max_length=50, null=True, verbose_name='interaction_energy')),
                ('figure', models.CharField(blank=True, max_length=500, null=True, verbose_name='figure')),
            ],
            options={
                'verbose_name': 'structure',
                'verbose_name_plural': 'structures',
                'ordering': ['id'],
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.AddField(
            model_name='capim_dsrna_information',
            name='offtarget_image',
            field=models.TextField(blank=True, null=True, verbose_name='offtarget_image'),
        ),
        migrations.AlterField(
            model_name='capim_dsrna_information',
            name='dsrna_seq',
            field=models.TextField(blank=True, null=True, verbose_name='dsrna_seq'),
        ),
        migrations.AlterField(
            model_name='capim_dsrna_information',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='capim_dsrna_information',
            name='start',
            field=models.IntegerField(blank=True, null=True, verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='capim_dsrna_information',
            name='stop',
            field=models.IntegerField(blank=True, null=True, verbose_name='stop'),
        ),
        migrations.AddField(
            model_name='capim_structure',
            name='dsrna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Capim_Dsrna_Information'),
        ),
        migrations.AddField(
            model_name='capim_structure',
            name='gene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Capim_Gene_Information'),
        ),
        migrations.AddField(
            model_name='capim_structure',
            name='organism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Organisms'),
        ),
        migrations.AddField(
            model_name='capim_on_targets',
            name='dsrna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Capim_Dsrna_Information'),
        ),
        migrations.AddField(
            model_name='capim_on_targets',
            name='gene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Capim_Gene_Information'),
        ),
        migrations.AddField(
            model_name='capim_on_targets',
            name='organism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Organisms'),
        ),
        migrations.AddField(
            model_name='capim_iscore',
            name='dsrna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Capim_Dsrna_Information'),
        ),
        migrations.AddField(
            model_name='capim_iscore',
            name='gene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Capim_Gene_Information'),
        ),
        migrations.AddField(
            model_name='capim_iscore',
            name='organism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Organisms'),
        ),
    ]
