# Generated by Django 2.0.4 on 2021-10-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssrnai', '0012_auto_20211013_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capim_dsrna_information',
            name='dsrna_seq',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='dsrna_seq'),
        ),
    ]
