# Generated by Django 2.0.4 on 2021-10-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssrnai', '0014_auto_20211014_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='conyza_dsrna_information',
            name='offtarget_image',
            field=models.TextField(blank=True, null=True, verbose_name='offtarget_image'),
        ),
        migrations.AddField(
            model_name='nematoide_dsrna_information',
            name='offtarget_image',
            field=models.TextField(blank=True, null=True, verbose_name='offtarget_image'),
        ),
        migrations.AlterField(
            model_name='conyza_dsrna_information',
            name='dsrna_seq',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='dsrna_seq'),
        ),
        migrations.AlterField(
            model_name='conyza_dsrna_information',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='conyza_dsrna_information',
            name='start',
            field=models.IntegerField(blank=True, null=True, verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='conyza_dsrna_information',
            name='stop',
            field=models.IntegerField(blank=True, null=True, verbose_name='stop'),
        ),
        migrations.AlterField(
            model_name='lagarta_dsrna_information',
            name='dsrna_seq',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='dsrna_seq'),
        ),
        migrations.AlterField(
            model_name='nematoide_dsrna_information',
            name='dsrna_seq',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='dsrna_seq'),
        ),
        migrations.AlterField(
            model_name='nematoide_dsrna_information',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='nematoide_dsrna_information',
            name='start',
            field=models.IntegerField(blank=True, null=True, verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='nematoide_dsrna_information',
            name='stop',
            field=models.IntegerField(blank=True, null=True, verbose_name='stop'),
        ),
    ]
