# Generated by Django 2.0.4 on 2021-10-15 12:50

from django.db import migrations, models
import django.db.models.deletion
import projeto.models.template


class Migration(migrations.Migration):

    dependencies = [
        ('ssrnai', '0015_auto_20211014_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conyza_Iscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_dsir', models.IntegerField(blank=True, null=True, verbose_name='rank_dsir')),
                ('rank_iscore', models.IntegerField(blank=True, null=True, verbose_name='rank_iscore')),
                ('rank_sbiopredsi', models.IntegerField(blank=True, null=True, verbose_name='rank_sbiopredsi')),
                ('mean_dsir', models.FloatField(blank=True, null=True, verbose_name='mean_dsir')),
                ('sum_dsir', models.FloatField(blank=True, null=True, verbose_name='sum_dsir')),
                ('max_dsir', models.FloatField(blank=True, null=True, verbose_name='max_dsir')),
                ('min_dsir', models.FloatField(blank=True, null=True, verbose_name='min_dsir')),
                ('count_dsir', models.FloatField(blank=True, null=True, verbose_name='count_dsir')),
                ('median_dsir', models.FloatField(blank=True, null=True, verbose_name='median_dsir')),
                ('std_dsir', models.FloatField(blank=True, null=True, verbose_name='std_dsir')),
                ('var_dsir', models.FloatField(blank=True, null=True, verbose_name='var_dsir')),
                ('mean_iscore', models.FloatField(blank=True, null=True, verbose_name='mean_iscore')),
                ('sum_iscore', models.FloatField(blank=True, null=True, verbose_name='sum_iscore')),
                ('max_iscore', models.FloatField(blank=True, null=True, verbose_name='max_iscore')),
                ('min_iscore', models.FloatField(blank=True, null=True, verbose_name='min_iscore')),
                ('count_iscore', models.FloatField(blank=True, null=True, verbose_name='count_iscore')),
                ('median_iscore', models.FloatField(blank=True, null=True, verbose_name='median_iscore')),
                ('std_iscore', models.FloatField(blank=True, null=True, verbose_name='std_iscore')),
                ('var_iscore', models.FloatField(blank=True, null=True, verbose_name='var_iscore')),
                ('mean_sbiopredsi', models.FloatField(blank=True, null=True, verbose_name='mean_iscore')),
                ('sum_sbiopredsi', models.FloatField(blank=True, null=True, verbose_name='sum_iscore')),
                ('max_sbiopredsi', models.FloatField(blank=True, null=True, verbose_name='max_iscore')),
                ('min_sbiopredsi', models.FloatField(blank=True, null=True, verbose_name='min_iscore')),
                ('count_sbiopredsi', models.FloatField(blank=True, null=True, verbose_name='count_iscore')),
                ('median_sbiopredsi', models.FloatField(blank=True, null=True, verbose_name='median_iscore')),
                ('std_sbiopredsi', models.FloatField(blank=True, null=True, verbose_name='std_iscore')),
                ('var_sbiopredsi', models.FloatField(blank=True, null=True, verbose_name='var_iscore')),
                ('dsrna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Conyza_Dsrna_Information')),
                ('gene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Conyza_Gene_Information')),
                ('organism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Organisms')),
            ],
            options={
                'verbose_name': 'iscore',
                'verbose_name_plural': 'iscores',
                'ordering': ['id'],
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.CreateModel(
            name='Conyza_On_Targets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_ontarget', models.IntegerField(blank=True, null=True, verbose_name='number_ontarget')),
                ('start_dsrna', models.IntegerField(blank=True, null=True, verbose_name='start_dsrna')),
                ('end_dsrna', models.IntegerField(blank=True, null=True, verbose_name='end_dsrna')),
                ('dsrna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Conyza_Dsrna_Information')),
                ('gene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Conyza_Gene_Information')),
                ('organism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Organisms')),
            ],
            options={
                'verbose_name': 'ontarget',
                'verbose_name_plural': 'ontargets',
                'ordering': ['id'],
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
        migrations.CreateModel(
            name='Conyza_Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mismatch', models.IntegerField(blank=True, null=True, verbose_name='mismatch')),
                ('match', models.IntegerField(blank=True, null=True, verbose_name='match')),
                ('composition', models.TextField(blank=True, null=True, verbose_name='composition')),
                ('classification', models.CharField(max_length=50, null=True, verbose_name='classification')),
                ('interaction_energy', models.FloatField(blank=True, max_length=50, null=True, verbose_name='interaction_energy')),
                ('figure', models.CharField(blank=True, max_length=500, null=True, verbose_name='figure')),
                ('dsrna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Conyza_Dsrna_Information')),
                ('gene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Conyza_Gene_Information')),
                ('organism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssrnai.Organisms')),
            ],
            options={
                'verbose_name': 'structure',
                'verbose_name_plural': 'structures',
                'ordering': ['id'],
            },
            bases=(models.Model, projeto.models.template.TemplateModelMixin),
        ),
    ]
