# Generated by Django 2.0.4 on 2021-10-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssrnai', '0018_conyza_expression_nematoide_expression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nematoide_gene_information',
            name='cds_seq',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='cds_seq'),
        ),
    ]
