# Generated by Django 2.0.4 on 2021-10-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssrnai', '0019_auto_20211015_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nematoide_gene_information',
            name='cds_seq',
            field=models.CharField(blank=True, max_length=6000, null=True, verbose_name='cds_seq'),
        ),
    ]
