# Generated by Django 2.0.4 on 2021-10-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssrnai', '0024_auto_20211016_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conyza_expression_description',
            name='treatment',
        ),
        migrations.AddField(
            model_name='conyza_expression_description',
            name='dataset',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='dataset'),
        ),
        migrations.AddField(
            model_name='conyza_expression_description',
            name='species',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='species'),
        ),
        migrations.AddField(
            model_name='conyza_expression_description',
            name='stage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='stage'),
        ),
        migrations.AlterField(
            model_name='conyza_expression_description',
            name='condition_description',
            field=models.TextField(blank=True, null=True, verbose_name='condition_description'),
        ),
        migrations.AlterField(
            model_name='conyza_expression_description',
            name='expression',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='expression_id'),
        ),
        migrations.AlterField(
            model_name='conyza_expression_description',
            name='ncbi_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ncbi_id'),
        ),
    ]
