# Generated by Django 2.0.4 on 2021-10-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssrnai', '0025_auto_20211016_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conyza_expression_description',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='conyza_expression_description',
            name='stage',
        ),
        migrations.AddField(
            model_name='conyza_expression_description',
            name='treatment',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='treatment'),
        ),
        migrations.AlterField(
            model_name='conyza_expression_description',
            name='species',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='species'),
        ),
    ]
