# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sequenciamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_contratacao',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
