# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 13:30
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sequenciamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaSequenciamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.CharField(choices=[('Definição de amostras', 'Definição de amostras'), ('Coleta', 'Coleta'), ('Extração de DNA', 'Extração de DNA'), ('Análise de qualidade', 'Análise de qualidade'), ('Preparo para envio', 'Preparo para envio'), ('Envio', 'Envio'), ('Outros', 'Outros')], max_length=64)),
                ('status', models.CharField(choices=[('Não Iniciado', 'Não Iniciado'), ('Em Execução', 'Em Execução'), ('Finalizado', 'Finalizado')], max_length=64)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_tarefasequenciamento', to=settings.AUTH_USER_MODEL)),
                ('sequenciamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequenciamento.Sequenciamento')),
            ],
            options={
                'verbose_name_plural': 'tarefasequenciamentos',
                'ordering': ['tarefa'],
                'verbose_name': 'tarefasequenciamento',
            },
        ),
    ]
