# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequenciamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposequenciamento',
            options={'ordering': ['nome'], 'verbose_name': 'tiposequenciamento', 'verbose_name_plural': 'tiposequenciamentos'},
        ),
    ]
