# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 18:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projeto', '0002_auto_20160422_1128'),
        ('sequenciamento', '0002_auto_20160429_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequenciamento',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.TextField(blank=True, null=True)),
                ('material_biologico', models.CharField(
                    blank=True, max_length=256)),
                ('descricao_material_biologico',
                 models.TextField(blank=True, null=True)),
                ('numero_amostras', models.IntegerField(blank=True)),
                ('status_contrato', models.CharField(choices=[('Contratado', 'Contratado'), (
                    'Em Contratação', 'Em Contratação'), ('Finalizado', 'Finalizadp')], max_length=64)),
                ('status_pagamento', models.CharField(choices=[
                 ('Atencipação', 'Atencipação'), ('Pendente', 'Pendente'), ('Pago', 'Pago')], max_length=64)),
                ('empresa_executora', models.CharField(blank=True, max_length=256)),
                ('data_contratacao', models.DateField(blank=True)),
                ('detalhamento_material', models.TextField(blank=True, null=True)),
                ('status_cgen', models.CharField(blank=True, max_length=128)),
                ('ttm', models.CharField(blank=True, max_length=128)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True,
                                                 on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='responsavel_sequenciamento', to=settings.AUTH_USER_MODEL)),
                ('tipo_sequenciamento', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='sequenciamento.TipoSequenciamento')),
            ],
            options={
                'verbose_name_plural': 'sequenciamentos',
                'ordering': ['material_biologico'],
                'verbose_name': 'sequenciamento',
            },
        ),
    ]
