# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequenciamento', '0002_auto_20160713_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequenciamento',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
