# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequenciamento', '0003_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequenciamento',
            name='projeto',
        ),
        migrations.AddField(
            model_name='sequenciamento',
            name='contrato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sequenciamento.Contrato'),
            preserve_default=False,
        ),
    ]
