# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequenciamento', '0003_sequenciamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequenciamento',
            name='codigo_pedido_gestor',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='sequenciamento',
            name='contato_gestor',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='sequenciamento',
            name='prioridade',
            field=models.CharField(choices=[(
                'Normal', 'Normal'), ('Urgente', 'Urgente')], default='Normal', max_length=64),
        ),
        migrations.AlterField(
            model_name='sequenciamento',
            name='status_cgen',
            field=models.CharField(blank=True, choices=[(
                'TTM - Preparado', 'TTM - Preparado'), ('TTM - Não Preparado', 'TTM - Não Preparado')], max_length=64),
        ),
        migrations.AlterField(
            model_name='sequenciamento',
            name='status_contrato',
            field=models.CharField(blank=True, choices=[('Contratado', 'Contratado'), ('Em Contratação', 'Em Contratação'), (
                'Em Cotação', 'Em Cotação'), ('Finalizado', 'Finalizado')], max_length=64),
        ),
        migrations.AlterField(
            model_name='sequenciamento',
            name='status_pagamento',
            field=models.CharField(blank=True, choices=[('Aviso de Fornecimento', 'Aviso de Fornecimento'), (
                'Atencipação', 'Atencipação'), ('Pendente', 'Pendente'), ('Pago', 'Pago')], max_length=64),
        ),
        migrations.AlterField(
            model_name='sequenciamento',
            name='ttm',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
