# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequenciamento', '0003_sequenciamento_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
