# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequenciamento', '0004_contrato_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='ttm',
            field=models.CharField(blank=True, choices=[('TTM - Preparado', 'TTM - Preparado'), ('TTM - Não Preparado', 'TTM - Não Preparado')], max_length=256, null=True),
        ),
    ]
