# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequenciamento', '0004_auto_20160502_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequenciamento',
            name='codigo_pedido_gestor',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sequenciamento',
            name='contato_gestor',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sequenciamento',
            name='data_contratacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sequenciamento',
            name='empresa_executora',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sequenciamento',
            name='numero_amostras',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sequenciamento',
            name='status_cgen',
            field=models.CharField(blank=True, choices=[(
                'TTM - Preparado', 'TTM - Preparado'), ('TTM - Não Preparado', 'TTM - Não Preparado')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sequenciamento',
            name='status_contrato',
            field=models.CharField(blank=True, choices=[('Contratado', 'Contratado'), ('Em Contratação', 'Em Contratação'), (
                'Em Cotação', 'Em Cotação'), ('Finalizado', 'Finalizado')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sequenciamento',
            name='status_pagamento',
            field=models.CharField(blank=True, choices=[('Aviso de Fornecimento', 'Aviso de Fornecimento'), (
                'Atencipação', 'Atencipação'), ('Pendente', 'Pendente'), ('Pago', 'Pago')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sequenciamento',
            name='ttm',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
