# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 13:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequenciamento', '0006_auto_20160504_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposequenciamento',
            name='nome',
            field=models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
