# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 13:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sequenciamento', '0007_auto_20160504_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequenciamento',
            name='colaborador',
            field=models.ManyToManyField(blank=True, related_name='colaborador_sequenciamento', to=settings.AUTH_USER_MODEL),
        ),
    ]
