# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 18:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequenciamento', '0008_sequenciamento_colaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequenciamento',
            name='material_biologico',
            field=models.CharField(max_length=256, validators=[
                                   django.core.validators.MinLengthValidator(5)]),
        ),
    ]
