# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fddb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fddb',
            name='complemento',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='fddb',
            name='organismo',
            field=models.CharField(choices=[('BR1', 'BR174'), ('COA', 'Coari'), ('MAN', 'Manicoré')], default='BR1', max_length=64),
        ),
    ]
